// Code generated by "doxxer . -h"; DO NOT EDIT.

/*
Lshid lists HID devices attached to the system.

Usage:

	lshid [-V] [-v] [-vid vendor] [-pid product]

Flags:

	-V	Print HIDAPI version and exit
	-pid product
	  	Show devices with matching product ID
	-v	Increase verbosity (show device information)
	-vid vendor
	  	Show devices with matching vendor ID

Report issues to https://github.com/sstallion/go-hid/issues.
*/
package main
