// Code generated by "stringer -type BusType -trimprefix=Bus"; DO NOT EDIT.

package hid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BusUnknown-0]
	_ = x[BusUSB-1]
	_ = x[BusBluetooth-2]
	_ = x[BusI2C-3]
	_ = x[BusSPI-4]
}

const _BusType_name = "UnknownUSBBluetoothI2CSPI"

var _BusType_index = [...]uint8{0, 7, 10, 19, 22, 25}

func (i BusType) String() string {
	if i < 0 || i >= BusType(len(_BusType_index)-1) {
		return "BusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BusType_name[_BusType_index[i]:_BusType_index[i+1]]
}
